### ISSUE TITLE
`@my_artifacts_toml!()` macro can possibly be avoided

### ISSUE THREAD

**Issue by rikhuijzer** [chengchingwen/MyArtifacts.jl#1]
The is a famous JuliaCon talk where someone said that macro's should be avoided as much as possible. I was looking through the source of this package and wonder whether the `@my_artifacts_toml!()` macro be avoided by passing the module manually?

So, use from the perspective of the user:

```
module MyModule

my_artifacts_toml!(MyModule)

end
```

The benefit is that this is more flexible because an user can now also edit the artifact outside of the current module.

**Comment by chengchingwen** [comment]
We do have both `my_artifacts_toml!` and `@my_artifacts_toml` and it does work as you said. I think it might be convenient to have `@my_artifacts_toml` because [Scratch.jl](https://github.com/JuliaPackaging/Scratch.jl) also have both `get_scratch!` and `@get_scratch!`.
